<?php

declare(strict_types=1);

use CimaAlfaCSFixers\Fixer\BracesPositionFixer;
use CimaAlfaCSFixers\Fixer\ClassAndTraitVisibilityRequiredFixer;
use CimaAlfaCSFixers\Fixer\MethodArgumentSpaceFixer;
use CimaAlfaCSFixers\Fixer\StatementIndentationFixer;
use PhpCsFixerCustomFixers\Fixer\CommentedOutFunctionFixer;
use PhpCsFixerCustomFixers\Fixer\MultilinePromotedPropertiesFixer;
use PhpCsFixerCustomFixers\Fixer\NoLeadingSlashInGlobalNamespaceFixer;

return [
    '@PSR12' => true,
    '@PSR12:risky' => true,
    '@PHP70Migration:risky' => true,
    '@PHP71Migration' => true,
    '@PHP73Migration' => true,
    '@PHP74Migration' => true,
    '@PHP80Migration' => true,
    '@PHP80Migration:risky' => true,
    '@PHP81Migration' => true,
    '@PHP82Migration' => true,
    '@PHP83Migration' => true,
    '@PHP84Migration' => true,
    'array_indentation' => true,
    'array_push' => true,
    'array_syntax' => [
        'syntax' => 'short',
    ],
    'backtick_to_shell_exec' => true,
    'binary_operator_spaces' => [
        'default' => 'single_space',
    ],
    'blank_line_after_namespace' => true,
    'blank_line_after_opening_tag' => true,
    'blank_line_before_statement' => [
        'statements' => [
            'continue',
            'return',
        ],
    ],
    'blank_line_between_import_groups' => true, 
    'blank_lines_before_namespace' => true, 
    'braces_position' => false, 
    'cast_spaces' => true, 
    'class_reference_name_casing' => true, 
    'combine_consecutive_issets' => true, 
    'combine_consecutive_unsets' => true, 
    'concat_space' => [
        'spacing' => 'one',
    ], 
    'control_structure_braces' => true, 
    'control_structure_continuation_position' => true, 
    'date_time_immutable' => true, 
    'declare_parentheses' => true, 
    'declare_strict_types' => true, 
    'dir_constant' => true, 
    'function_declaration' => [
        'closure_fn_spacing' => 'none',
    ], 
    'final_internal_class' => true, 
    'final_public_method_for_abstract_class' => true, 
    'fully_qualified_strict_types' => true, 
    'global_namespace_import' => [
        'import_classes' => true, 
        'import_constants' => true, 
        'import_functions' => true,
    ], 
    'heredoc_to_nowdoc' => true, 
    'include' => true, 
    'indentation_type' => true, 
    'is_null' => true, 
    'linebreak_after_opening_tag' => true, 
    'lowercase_keywords' => true, 
    'lowercase_static_reference' => true, 
    'magic_constant_casing' => true, 
    'mb_str_functions' => true, 
    'method_argument_space' => false, 
    'modernize_types_casting' => true, 
    'native_function_casing' => true, 
    'new_with_parentheses' => false, 
    'no_alias_functions' => true, 
    'no_alternative_syntax' => true, 
    'no_break_comment' => [
        'comment_text' => 'break omitted',
    ], 
    'no_empty_comment' => true, 
    'no_empty_phpdoc' => true, 
    'no_empty_statement' => true, 
    'no_leading_namespace_whitespace' => true, 
    'no_multiple_statements_per_line' => true, 
    'no_null_property_initialization' => true, 
    'no_short_bool_cast' => true, 
    'no_singleline_whitespace_before_semicolons' => true, 
    'no_spaces_around_offset' => true, 
    'no_superfluous_elseif' => true, 
    'no_trailing_comma_in_singleline' => true, 
    'no_trailing_whitespace' => true, 
    'no_unneeded_braces' => true, 
    'no_unneeded_control_parentheses' => true, 
    'no_unset_on_property' => true, 
    'no_useless_else' => true, 
    'no_whitespace_before_comma_in_array' => true, 
    'no_whitespace_in_blank_line' => true, 
    'non_printable_character' => false, 
    'normalize_index_brace' => true, 
    'nullable_type_declaration_for_default_null_value' => true, 
    'object_operator_without_whitespace' => true, 
    'ordered_class_elements' => [
        'order' => [
            'use_trait', 
            'case', 
            'constant', 
            'constant_public', 
            'constant_protected', 
            'constant_private', 
            'property_public', 
            'property_protected', 
            'property_private', 
            'construct', 
            'destruct', 
            'magic', 
            'phpunit', 
            'method_abstract', 
            'method_public_static', 
            'method_public', 
            'method_protected_static', 
            'method_protected', 
            'method_private_static', 
            'method_private',
        ],
    ], 
    'ordered_imports' => [
        'imports_order' => [
            'class', 
            'function', 
            'const',
        ],
    ], 
    'ordered_interfaces' => true, 
    'ordered_traits' => true, 
    'phpdoc_indent' => true, 
    'phpdoc_trim' => true, 
    'phpdoc_trim_consecutive_blank_line_separation' => true, 
    'phpdoc_types' => true, 
    'protected_to_private' => true, 
    'random_api_migration' => false, 
    'self_accessor' => true, 
    'self_static_accessor' => true, 
    'set_type_to_cast' => true, 
    'simple_to_complex_string_variable' => true, 
    'single_import_per_statement' => false, 
    'single_line_after_imports' => true, 
    'single_line_comment_style' => [
        'comment_types' => [
            'hash',
        ],
    ], 
    'single_quote' => true, 
    'single_space_around_construct' => true, 
    'space_after_semicolon' => true, 
    'standardize_increment' => true, 
    'standardize_not_equals' => true, 
    'statement_indentation' => false, 
    'strict_comparison' => true, 
    'strict_param' => true, 
    'string_implicit_backslashes' => true, 
    'ternary_to_elvis_operator' => true, 
    'trailing_comma_in_multiline' => [
        'elements' => [
            'arrays',
        ],
    ], 
    'trim_array_spaces' => true, 
    'unary_operator_spaces' => true, 
    'visibility_required' => false, 
    'void_return' => false, 
    'whitespace_after_comma_in_array' => true, 
    BracesPositionFixer::name() => true, 
    CommentedOutFunctionFixer::name() => [
        'dump', 
        'print_r', 
        'var_dump', 
        'var_export',
    ], 
    ClassAndTraitVisibilityRequiredFixer::name() => true,
    MethodArgumentSpaceFixer::name() => [
        'on_multiline' => 'ensure_fully_multiline',
    ], 
    MultilinePromotedPropertiesFixer::name() => true, 
    NoLeadingSlashInGlobalNamespaceFixer::name() => true, 
    StatementIndentationFixer::name() => [
        'stick_comment_to_next_continuous_control_statement' => true,
    ], 
]; 
 